# Generated by Django 5.1.7 on 2025-03-25 18:43

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager')], default='employee', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('alternative_number', models.CharField(blank=True, max_length=15, null=True)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('qualifications', models.CharField(max_length=255)),
                ('married_status', models.BooleanField(default=False)),
                ('current_address', models.TextField()),
                ('landmark', models.CharField(max_length=255)),
                ('years_at_address', models.IntegerField()),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('office_name', models.CharField(max_length=255)),
                ('office_address', models.TextField()),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('current_experience', models.IntegerField()),
                ('overall_experience', models.IntegerField()),
                ('reference_name_1', models.CharField(max_length=255)),
                ('reference_number_1', models.CharField(max_length=15)),
                ('reference_name_2', models.CharField(max_length=255)),
                ('reference_number_2', models.CharField(max_length=15)),
                ('expected_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_purpose', models.TextField()),
                ('client_type', models.CharField(choices=[('direct', 'Direct Client'), ('employee_registered', 'Employee-Registered Client')], default='direct', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_employee', models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cibil_score', models.IntegerField(blank=True, null=True)),
                ('aadhaar_front', models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path)),
                ('aadhaar_back', models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path)),
                ('cibil_report', models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path)),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path)),
                ('gas_bill', models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path)),
                ('reference_number_1', models.CharField(max_length=15)),
                ('reference_number_2', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_details', to='myapp.client')),
                ('filled_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_client_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
