# Generated by Django 5.1.7 on 2025-03-24 08:20

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeclientdetails',
            name='aadhaar_back',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path),
        ),
        migrations.AlterField(
            model_name='employeeclientdetails',
            name='aadhaar_front',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path),
        ),
        migrations.AlterField(
            model_name='employeeclientdetails',
            name='cibil_report',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path),
        ),
        migrations.AlterField(
            model_name='employeeclientdetails',
            name='gas_bill',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path),
        ),
        migrations.AlterField(
            model_name='employeeclientdetails',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.client_document_path),
        ),
    ]
