# Generated by Django 5.1.7 on 2025-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employeeclientdetails_aadhaar_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeclientdetails',
            name='cibil_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
