# Generated by Django 5.1.7 on 2025-03-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employeeclientdetails_cibil_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
