# Generated by Django 5.1.7 on 2025-03-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_clienttarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttarget',
            name='client',
        ),
    ]
