# Generated by Django 5.1.7 on 2025-03-26 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_clienttarget_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientattendance',
            name='filled_by_employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_by_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
