# Generated by Django 5.1.7 on 2025-03-29 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_monthlytarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytarget',
            name='month',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlytarget',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
