# Generated by Django 5.1.7 on 2025-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_monthlytarget_month_alter_monthlytarget_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('proceed', 'Proceed')], default='pending', max_length=10),
        ),
    ]
